services:
  # Web Service cho Node.js API
  - type: web
    name: ev-service-center-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push
      npm run db:fix
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ev-service-center-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://ev-service-center-api.onrender.com/api/auth/google/callback
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  # PostgreSQL Database
  - type: pserv
    name: ev-service-center-db
    env: postgresql
    plan: free
    region: singapore
    ipAllowList: []
    maxConnections: 97
    disk:
      name: ev-service-center-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
