openapi: 3.0.0
info:
  title: EV Service Center API
  description: Tài liệu API tổng hợp cho hệ thống Trung tâm Dịch vụ Xe điện.
  version: 1.0.0
servers:
  - url: http://localhost:6969/api
    description: Development server

tags:
  - name: Auth
    description: Các endpoint liên quan đến đăng ký, đăng nhập và Google OAuth.
  - name: Profile
    description: Quản lý thông tin cá nhân của người dùng đã đăng nhập.
  - name: Admin
    description: Các chức năng chỉ dành cho quản trị viên (Admin).

paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Đăng ký tài khoản mới
      description: Tạo một tài khoản người dùng mới với vai trò mặc định là CUSTOMER.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInput'
      responses:
        '201':
          description: Tài khoản được tạo thành công.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Dữ liệu không hợp lệ hoặc email đã tồn tại.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      tags: [Auth]
      summary: Đăng nhập vào hệ thống
      description: Xác thực người dùng bằng email và mật khẩu, trả về JWT token nếu thành công.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: Đăng nhập thành công.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Email hoặc mật khẩu không chính xác.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /auth/google:
    get:
      tags: [Auth]
      summary: Bắt đầu đăng nhập với Google
      description: Điều hướng người dùng đến trang xác thực của Google. Người dùng không gọi trực tiếp API này mà thông qua một link trên frontend.
      responses:
        '302':
          description: Chuyển hướng đến trang đăng nhập Google.

  /auth/google/callback:
    get:
      tags: [Auth]
      summary: Callback sau khi Google xác thực
      description: Google sẽ gọi lại endpoint này sau khi người dùng xác thực thành công. Backend xử lý và trả về JWT token.
      responses:
        '200':
          description: Xác thực thành công.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleOAuthResponse'
        '401':
          description: Xác thực thất bại.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/profile:
    get:
      tags: [Profile]
      summary: Lấy thông tin cá nhân
      description: Lấy thông tin chi tiết của người dùng đang đăng nhập. Yêu cầu JWT token.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lấy thông tin thành công.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Chưa xác thực hoặc token không hợp lệ.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /admin/users:
    get:
      tags: [Admin]
      summary: Lấy danh sách tất cả tài khoản
      description: (Chỉ Admin) Lấy danh sách tất cả tài khoản người dùng trong hệ thống. Yêu cầu JWT token của Admin.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lấy danh sách thành công.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Chưa xác thực.
        '403':
          description: Không có quyền truy cập (không phải Admin).

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fullName:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [CUSTOMER, STAFF, TECHNICIAN, INVENTORY_MANAGER, ADMIN, STATION_ADMIN]

    RegisterInput:
      type: object
      required: [fullName, email, password]
      properties:
        fullName:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    LoginInput:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    LoginResponse:
      type: object
      properties:
        message:
          type: string
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'

    GoogleOAuthResponse:
      type: object
      properties:
        message:
          type: string
          example: "Google authentication successful"
        token:
          type: string
          description: JWT token for authentication
        user:
          $ref: '#/components/schemas/User'

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Nhập JWT token để xác thực. Ví dụ: 'Bearer {token}'"
